pimcore_data_hub:
    configurations:
        2312321:
            general:
                type: graphql
                path: null
                name: '2312321'
                modificationDate: 1708918346
                createDate: 1708918346
            workspaces: {  }
            permissions:
                user: {  }
                role: {  }
