pimcore_data_hub:
    configurations:
        addproduct:
            general:
                type: dataImporterDataObject
                name: addproduct
                description: ''
                group: ''
                active: false
                path: null
                modificationDate: 1705669321
                createDate: 1703712595
            loaderConfig:
                type: upload
                settings:
                    uploadFilePath: addproduct/upload.import
            interpreterConfig:
                type: xlsx
                settings:
                    skipFirstRow: true
                    sheetName: addproduct
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '6'
                loadingStrategy:
                    type: attribute
                    settings:
                        dataSourceIndex: '0'
                        attributeName: itemnumber
                        language: ''
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: description
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: noChangePublishNew
            processingConfig:
                executionType: parallel
                idDataIndex: ''
            mappingConfig:
                -
                    label: 'itemnumber [0]'
                    dataSourceIndex:
                        - '0'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: itemnumber
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'status [1]'
                    dataSourceIndex:
                        - '1'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: status
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'packingtype [2]'
                    dataSourceIndex:
                        - '2'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: packingtype
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'productsize [3]'
                    dataSourceIndex:
                        - '3'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: productsize
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: 'productname [4]'
                    dataSourceIndex:
                        - '4'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: productname
                            language: uk
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'enname [5]'
                    dataSourceIndex:
                        - '5'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: productname
                            language: en
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
            executionConfig:
                scheduleType: recurring
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
