pimcore_data_hub:
    configurations:
        qqqqq:
            general:
                type: graphql
                path: null
                name: qqqqq
                modificationDate: 1707913509
                createDate: 1707913509
            workspaces: {  }
            permissions:
                user: {  }
                role: {  }
