doctrine_migrations:
    connection: postgres
    migrations_paths:
        'App\PimCore\Admin\SettingQueries\Infrastructure\Databases\Migrations': '%kernel.project_dir%/src/PimCore/Admin/SettingQueries/Infrastructure/Databases/Migrations'
    enable_profiler: false
