doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'App\PimCore\Admin\SettingQueries\Infrastructure\Databases\Migrations': '%kernel.project_dir%/src/PimCore/Admin/SettingQueries/Infrastructure/Databases/Migrations'
    enable_profiler: false
