imports:
    - { resource: messengers/product_info/products/products.yaml }
    - { resource: messengers/shared/shared.yaml }
    - { resource: messengers/magento/products.yaml }
framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(RABBITMQ_URL)%'
            pimCore.products.import:
                dsn: '%env(MESSENGER_EVENTS_DSN)%'
                options:
                    exchange:
                        type: topic
                        name: pimcore.products
                    queues:
                        pimCore.products.imports:
                            binding_keys:
                                - 'products.import.*'

        routing:
            # Route your messages to the transports
            'App\MessageHandler\SampleMessage': async

