version: '3.8'

services:
    postgres-test:
        image: postgres:latest
        environment:
            POSTGRES_USER: pimcore
            POSTGRES_PASSWORD: pimcore
            POSTGRES_DB: pimcore
        ports:
            - "5532:5432"
        volumes:
            - ${HOME}/data/pimcore-gw-dev/postgresql:/var/lib/postgresql/data
