pimcore:
    general:
        domain: ''
        redirect_to_maindomain: false
        language: uk
        valid_languages:
            - en
            - uk
        fallback_languages:
            en: ''
            uk: ''
        default_language: uk
        debug_admin_translations: false
    documents:
        versions:
            days: null
            steps: null
        error_pages:
            default: ''
            localized:
                en: ''
                uk: ''
    objects:
        versions:
            days: null
            steps: null
    assets:
        versions:
            days: null
            steps: null
    email: {  }
